const dbCols = ["id","booking_id","booking_date","pickup_datetime","trip_type","pickup_location","drop_location","route","number_of_days","booking_status","customer_name","customer_mobile","alternate_mobile","customer_email","booking_source","service_vehicle_type","driver_ownership","vehicle_ownership","served_by","vendor_name","vendor_mobile","platform_name","panel_owner","driver_name","driver_mobile","vehicle_number","vehicle_model","vehicle_category","fuel_type","total_booking_amount","my_amount","vendor_amount","driver_amount","vendor_final_amount","commission_percentage","commission_amount","my_booking_amount","cash_collection_amount","paytm_collection_amount","upi_collection_amount","bank_collection_amount","collection_total","total_trip_expenses","profit","pending_recovery_amount","payable_amount","receivable_amount","extra_collection_amount","pending_extra_collection","payment_status","settlement_status","review_status","reminder_date","notes","created_at","collection_done_by","collection_mode","received_amount","customer_paid_amount","collection_received_date","collection_confirmed","next_reminder_date","expense_cng","expense_petrol_filled","expense_petrol_running_km","expense_toll","expense_state_tax","expense_parking","expense_food","expense_driver_advance","expense_other","source_category","source_name","application_name","group_name","advance_paytm_amount","advance_payment_status","advance_payment_date","advance_notes","pickup_date","pickup_time","rental_package","covered_locations","cng_entries","toll_entries","is_deleted","deleted_at","deleted_category","vehicle_brand","vehicle_name","review_method","video_review_status","video_review_date","review_link_sent","review_link_sent_date","review_received","rating","review_url","follow_up_required"];

const payloadCols = ['booking_id','source_category','source_name','application_name','group_name','advance_paytm_amount','advance_payment_status','advance_payment_date','advance_notes','service_vehicle_type','driver_ownership','vehicle_ownership','booking_status','booking_date','pickup_datetime','pickup_date','pickup_time','trip_type','rental_package','number_of_days','pickup_location','drop_location','covered_locations','route','notes','customer_name','customer_mobile','alternate_mobile','customer_email','vendor_name','vendor_mobile','panel_owner','vendor_platform_name','driver_name','driver_mobile','vehicle_number','vehicle_model','vehicle_brand','vehicle_category','fuel_type','my_amount','vendor_amount','driver_amount','total_booking_amount','commission_percentage','commission_amount','collection_done_by','collection_mode','cash_collection_amount','paytm_collection_amount','upi_collection_amount','bank_collection_amount','collection_total','total_trip_expenses','cng_entries','toll_entries','expense_cng','expense_petrol_filled','expense_petrol_running_km','expense_toll','expense_state_tax','expense_parking','expense_food','expense_driver_advance','expense_other','profit','pending_recovery_amount','payable_amount','receivable_amount','extra_collection_amount','pending_extra_collection','review_method','video_review_status','video_review_date','review_link_sent','review_link_sent_date','review_received','rating','review_url','follow_up_required'];

const missingInDb = payloadCols.filter(col => !dbCols.includes(col));
const unusedInDb = dbCols.filter(col => !payloadCols.includes(col));

console.log('--- MISSING IN DATABASE (PAYLOAD KEYS NOT IN DB) ---');
console.log(missingInDb);
console.log('\n--- UNUSED IN DATABASE (DB COLS NOT IN PAYLOAD) ---');
console.log(unusedInDb);
